//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobhunt.Models
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class JobApplications
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> JobApplDateTime { get; set; }
        public string JobApplName { get; set; }
        public string VacancyTitle { get; set; }
        public string VacancyText { get; set; }
        public string VacancyContactPerson { get; set; }
        public string VacancyContactPersonLinkedIn { get; set; }
        public string VacancyCompany { get; set; }
        public string VacancyCompanyCity { get; set; }
        public string VacancyCompanyStreetName { get; set; }
        public string VacancyCompanyStreetNumber { get; set; }
        public string VacancyCompanyZipCode { get; set; }
        public string JobApplFeedback { get; set; }
        public string VacancyLink { get; set; }
        public string JobApplStatus { get; set; }
        public string VacancyFunctionTitle { get; set; }
        public string VacancyCompanyWebsite { get; set; }
        public string JobApplNote { get; set; }
        public string JobApplTime { get; set; }
        public string JobApplLetter { get; set; }
        public Nullable<System.DateTime> JobApplInterviewDateTime { get; set; }
        public string JobApplInterviewTime { get; set; }
        public Nullable<System.DateTime> JobApplSecInterviewDateTime { get; set; }
        public string JobApplSecInterviewTime { get; set; }
        public string VacancyContactPersonEmail { get; set; }
        public string VacancyCompanyCountry { get; set; }
        public string VacancyCareerField { get; set; }
        public Nullable<System.DateTime> JobApplThirdInterviewDateTime { get; set; }
        public string JobApplThirdInterviewTime { get; set; }
        public string JobApplInterviewPersons { get; set; }
        public string JobApplSecInterviewPersons { get; set; }
        public string JobApplThirdInterviewPersons { get; set; }
        public string JobApplMyRating { get; set; }
        public string JobApplInterviewPreperation { get; set; }
        public string JobApplMyQuestions { get; set; }
        public string JobApplCompanyQuestions { get; set; }
        public string VacancySalary { get; set; }
        public string VacancyCompanySummary { get; set; }
        public string JobApplMyFollowUpEmails { get; set; }
        public string JobApplFollowUpStatus { get; set; }
        public string JobApplMethod { get; set; }
        public string JobApplInterviewNotes { get; set; }
        public int UserUserId { get; set; }
        public string ShowToFriends { get; set; }
        public string JobApplCat { get; set; }
    }
}
