//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobhunt.Models
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class User
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string StreetName { get; set; }
        public string StreetNumber { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string LinkedIn { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string MainCareer { get; set; }
        public string SubCareer { get; set; }
        public string Friends { get; set; }
        public string SearchTag { get; set; }
        public string FriendsInvRecieved { get; set; }
        public string FriendsInvSend { get; set; }
        public string Resume { get; set; }
        public string Categories { get; set; }
    }
}
